### PR TITLE
Endpoint switching

### LINKED ISSUE #92: gsctl commands ignore --auth-token given via flag
This should actually trigger a "not authenticated" error:
```
gsctl --api-endpoint=https://api-g8s.giantswarm.io list clusters --auth-token=sfdsdf
```

But it doesn't.

### PR DESCRIPTION
**Pull request by marians**
Implementation of #47

Fixes #92 along the way (making use of `--auth-token`)

### Information for testers

When released, this sort if information will be communicated to users via the CHANGELOG and also in the docs and README.

##### Config is partly incompatible with previous versions

The configuration file (by default: `$HOME/.config/gsctl/config.yaml`) will be overwritten with per-endpoint auth data. Switching between the a released version and this version will mean that you'll have to re-login and endpoint info gets lost.

##### Logging in, adding and selecting endpoint:

```nohighlight
gsctl login <email> -e <endpoint>
```

##### Listing all endpoints:

```nohighlight
gsctl list endpoints
```

##### Switching to a different endpoint:

```nohighlight
gsctl select endpoint <endpoint>
```

Alternatively, the environment variable `GSCTL_ENDPOINT` can be defined or the flag `-e`/`--endpoint` can be used with every command. Flag overwrites variable. Variable overwrites selected endpoint.

##### Check what's the current endpoint:

Two options:

```nohighlight
gsctl info
gsctl list endpoints
```

### Changes

- Removed default API endpoint logic
- Added global `-e` / `--endpoint` flag
- Marked `--api-endpoint` flag as deprecated
- Removed `microkit` dependency, replaced with `microerror`
- Removed dependency `github.com/spf13/viper`, as it doesn't help us with our nested config file
- `gsctl info` now also prints whether or not the user is logged in
- Config will now keep the email address of a user after logout. This enables re-login without having to add the email again to `gsctl login`.
- `config.Initialize()` now resets the config struct, to make test cases work.
- `gsctl logout` now gives output.
- If the endpoint is set via a flag (`-e`/`--endpoint`) the auth logic is as follows: If a token is given via command line flag, that one is used. Otherwise, if a token is stored for the endpoint, that one is used. Otherwise we don't have a token.

### TODO

- [x] Let `gsctl login` add new endpoint if unknown endpoint URL is used
- [x] Normalize API endpoint URL entered by user as `-e` or `--endpoint` flag. Add `https://`, remove trailing slash, remove default port 443 for HTTPS or 80 for HTTP.
- [x] Let `gsctl list endpoints` print all endpoint URLs from config
- [x] Let `gsctl select endpoint ...` switch endpoints
- [x] When `GSCTL_ENDPOINT=foo ./gsctl list endpoints` is executed, non of the listed endpoints must be selected.
- [x] Implement evaluation of environment variable `GSCTL_ENDPOINT`
- [x] Gracefully handle execution of `gsctl login` without an endpoint flag
- [x] For every command, make sure endpoint selection order is flag > env variable > selected endpoint
- [x] The selection which auth token is used should depend on the endpoint selection logic. If the endpoint is given via `-e` flag or coming from the env variable, the token should come from a flag (or from a variable). The selected endpoint's token may only be used if it's the same as given via flag/variable.

### CODE REVIEW

**Comment by oponder** [comment]
When using the `-e` flag, what auth token gets used? It seems to use the auth token of the currently selected endpoint. This will only work if the endpoint the user specifies with -e is the same as the currently selected endpoint.

In all other cases, this will probably never lead to a satisfying result.

Suggestion:

- Use the auth token for the given endpoint if it exists in the config
- And, complain that the user has never logged in with a given endpoint if there is no entry for it in the config.
- Don't complain or try to use any stored auth token if the user also provides the auth token flag.

**Comment by marians** [comment]
@oponder Commit https://github.com/giantswarm/gsctl/pull/120/commits/04fe700c9e597f1c2d3627c84d85f474e4329271 brings the change you requested. The behaviour of `config.ChooseToken`:

```
ChooseToken chooses a token to use, according to a rule set.
- If the given token is not empty, we use (return) that
- If the given token is empty and we have an auth token for the given
  endpoint, we return that
- otherwise we return an empty string
```

**Comment by oponder** [comment]
WFM!

File: client/error.go [hunk 1]
```diff
@@ -0,0 +1,11 @@
+package client
+
+import "github.com/juju/errgo"
+
+// attempt to create a client without endpoint
+var endpointNotSpecifiedError = errgo.New("no endpoint has been specified")
```
Comment (kopiczko) [inline client/error.go]: Godoc usually starts with the variable/member/function name.

File: client/client.go [hunk 2]
```diff
@@ -37,6 +37,11 @@ type GenericResponse struct {
 // with specific configuration
 func NewClient(clientConfig Configuration) (*gsclientgen.DefaultApi, error) {
 	configuration := gsclientgen.NewConfiguration()
+
+	if clientConfig.Endpoint == "" {
+		return &gsclientgen.DefaultApi{}, microerror.Mask(endpointNotSpecifiedError)
+	}
```
Comment (kopiczko) [inline client/client.go]: We ususally use

```
var invalidConfigError = microerror.New("invalid config")

// IsInvalidConfig asserts invalidConfigError.
func IsInvalidConfig(err error) bool {
	return microerror.Cause(err) == invalidConfigError
}
```
And then

```
return nil, microerror.Maskf(invalidConfigError, "endpoint must not be empty")
```

File: commands/commands_test.go [hunk 3]
```diff
@@ -0,0 +1,66 @@
...
+	"io/ioutil"
+	"os"
+	"path"
+
+	"github.com/giantswarm/gsctl/config"
+)
+
+// create a temporary directory
+func tempDir() string {
+	dir, _ := ioutil.TempDir("", config.ProgramName)
```
Comment (kopiczko) [inline commands/commands_test.go]: I know it's out of scope, but: I don't think ignoring this error is a good idea. You can either pass `t  *testing.T` and call `t.Fail` or `panic`.

File: commands/list_endpoints.go [hunk 4]
```diff
@@ -0,0 +1,68 @@
...
+
+// endpointsTable returns a table of clusters the user has access to
+func endpointsTable() string {
+	if len(config.Config.Endpoints) == 0 {
+		return fmt.Sprintf("No endpoints configured.\n\nTo add an endpoint and authenticate for it, use\n\n\t%s\n",
+			color.YellowString("gsctl login <email> -e <endpoint>"))
+	}
+
+	// table headers
+	output := []string{color.CyanString("ENDPOINT URL") + "|" + color.CyanString("EMAIL") + "|" + color.CyanString("SELECTED") + "|" + color.CyanString("LOGGED IN")}
```
Comment (kopiczko) [inline commands/list_endpoints.go]: You can use `strings.Join` to shorten those lines. https://golang.org/pkg/strings/#Join

File: commands/list_endpoints_test.go [hunk 5]
```diff
@@ -0,0 +1,31 @@
...
+	dir, err := tempConfig(yamlText)
+	if err != nil {
+		t.Error(err)
+	}
+	defer os.RemoveAll(dir)
+
+	table := endpointsTable()
+	if table == "" {
+		t.Error("Got no output where I expected a table")
+	}
```
Comment (kopiczko) [inline commands/list_endpoints_test.go]: Why not test against actual output?

File: commands/list_keypairs_test.go [hunk 6]
```diff
@@ -5,22 +5,20 @@ import (
...
+		t.Error(err)
+	}
 	defer os.RemoveAll(dir)
-	config.Initialize(dir)
-	config.Config.Token = ""
 
 	args := listKeypairsArguments{}
-	err := listKeypairsValidate(&args)
+	err = listKeypairsValidate(&args)
 	if err == nil {
```
Comment (kopiczko) [inline commands/list_keypairs_test.go]: You can use matcher function to check if this is the desired error.

File: commands/logout.go [hunk 7]
```diff
@@ -42,33 +40,30 @@ type logoutArguments struct {
...
 	RootCommand.AddCommand(LogoutCommand)
 }
 
-// TODO: separate validation and validation result output
-func logoutValidationOutput(cmd *cobra.Command, args []string) error {
+func logoutValidationOutput(cmd *cobra.Command, args []string) {
 	if config.Config.Token == "" && cmdToken == "" {
-		return errors.New("You are not logged in")
+		fmt.Println("You weren't logged in here, but better be safe than sorry.")
+		os.Exit(1)
```
Comment (kopiczko) [inline commands/logout.go]: Why is it better to exit immediately than return error?

File: config/config.go [hunk 8]
```diff
@@ -75,29 +69,141 @@ var (
...
+
+	// Email is the user email found for the selected endpoint. Might be empty.
+	// Not marshalled back to the config file, as it is contained in the
+	// endpoint's entry.
+	Email string `yaml:"-"`
+}
+
+// endpointConfigStruct is used to serialize/deserialize endpoint configuration
+// to/from a config file
+type endpointConfigStruct struct {
```
Comment (kopiczko) [inline config/config.go]: Having `Struct` suffix in a struct name is a little bit awkward.

File: config/config.go [hunk 9]
```diff
@@ -75,29 +69,141 @@ var (
...
+func (c *configStruct) Logout(endpointURL string) {
+	ep := normalizeEndpoint(endpointURL)
+
+	if ep == c.SelectedEndpoint {
+		c.Token = ""
+	}
+
+	if element, ok := c.Endpoints[ep]; ok {
+		element.Token = ""
+	}
```
Comment (kopiczko) [inline config/config.go]: Why not `delete(c.Endpoints, ep)`?

File: config/config.go [hunk 10]
```diff
@@ -120,23 +225,19 @@ func init() {
 // It's supposed to be called after init().
 // The configDirPath argument can be given to override the DefaultConfigDirPath.
 func Initialize(configDirPath string) error {
+	// Reset our Config object. This is particularly necessary for running
+	// multiple tests in a row.
+	Config = configStruct{}
```
Comment (kopiczko) [inline config/config.go]: I really dislike this is a global variable. This also makes `WriteToFile` very magical.

File: client/error.go (hunk 1 above)
Comment (marians) [reply client/error.go]: I do that for exported variables (uppercase first letter), but not for non exported ones. IMHO the dublication makes the comment harder to read directly in the code.

File: client/client.go (hunk 2 above)
Comment (marians) [reply client/client.go]: Cool. Learnt something new. That improves things. Can we keep that to a new PR? I basically tried to swap microkit with microerrer (which I understand was a mistake in hindsight)

File: commands/commands_test.go (hunk 3 above)
Comment (marians) [reply commands/commands_test.go]: panic makes sense. It's used in tests only, so a non-graceful exit would be fine.

File: client/error.go (hunk 1 above)
Comment (kopiczko) [reply client/error.go]: > IMHO the duplication makes the comment harder to read directly in the code.

I understand it doesn't fit your personal taste. This is established convention, so let's conform.

File: commands/list_endpoints.go (hunk 4 above)
Comment (marians) [reply commands/list_endpoints.go]: Very handy!

File: commands/logout.go (hunk 7 above)
Comment (marians) [reply commands/logout.go]: Because this we way can influence the error output shown to the user. If we would return an error here, cobra would show the error text and the entire command usage.

File: config/config.go (hunk 8 above)
Comment (marians) [reply config/config.go]: Yeah. Changed.

File: config/config.go (hunk 9 above)
Comment (marians) [reply config/config.go]: I want to keep the endpoint entry with the email address stored (`element.Email`), to simplify future logins.

File: config/config.go (hunk 10 above)
Comment (marians) [reply config/config.go]: What would be a better way?

Comment (kopiczko) [reply config/config.go]: I checked out the code.
What is confusing that there are methods of the config struct itself, functions (i.e. `WriteToFile`) which rely on the fact that `config.Config` is a global variable.

I'd be ok for me if either `WriteToFile` took a config argument or config struct had method `WriteToFile`.

**Comment by marians** [comment]
@kopiczko Does this get your approval?
